import * as React from 'react'
import Svg, { Path, SvgProps } from 'react-native-svg'
export const EyeOffIcon = (
 props: React.JSX.IntrinsicAttributes &
  React.JSX.IntrinsicClassAttributes<Svg> &
  Pick<
   Readonly<SvgProps>,
   | 'pointerEvents'
   | 'color'
   | 'fontSize'
   | 'fontFamily'
   | 'letterSpacing'
   | 'children'
   | 'hitSlop'
   | 'id'
   | 'needsOffscreenAlphaCompositing'
   | 'onLayout'
   | 'removeClippedSubviews'
   | 'style'
   | 'testID'
   | 'nativeID'
   | 'collapsable'
   | 'renderToHardwareTextureAndroid'
   | 'focusable'
   | 'tabIndex'
   | 'shouldRasterizeIOS'
   | 'isTVSelectable'
   | 'hasTVPreferredFocus'
   | 'tvParallaxProperties'
   | 'tvParallaxShiftDistanceX'
   | 'tvParallaxShiftDistanceY'
   | 'tvParallaxTiltAngle'
   | 'tvParallaxMagnification'
   | 'onStartShouldSetResponder'
   | 'onMoveShouldSetResponder'
   | 'onResponderEnd'
   | 'onResponderGrant'
   | 'onResponderReject'
   | 'onResponderMove'
   | 'onResponderRelease'
   | 'onResponderStart'
   | 'onResponderTerminationRequest'
   | 'onResponderTerminate'
   | 'onStartShouldSetResponderCapture'
   | 'onMoveShouldSetResponderCapture'
   | 'onTouchStart'
   | 'onTouchMove'
   | 'onTouchEnd'
   | 'onTouchCancel'
   | 'onTouchEndCapture'
   | 'onPointerEnter'
   | 'onPointerEnterCapture'
   | 'onPointerLeave'
   | 'onPointerLeaveCapture'
   | 'onPointerMove'
   | 'onPointerMoveCapture'
   | 'onPointerCancel'
   | 'onPointerCancelCapture'
   | 'onPointerDown'
   | 'onPointerDownCapture'
   | 'onPointerUp'
   | 'onPointerUpCapture'
   | 'accessible'
   | 'accessibilityActions'
   | 'accessibilityLabel'
   | 'aria-label'
   | 'accessibilityRole'
   | 'accessibilityState'
   | 'aria-busy'
   | 'aria-checked'
   | 'aria-disabled'
   | 'aria-expanded'
   | 'aria-selected'
   | 'accessibilityHint'
   | 'accessibilityValue'
   | 'aria-valuemax'
   | 'aria-valuemin'
   | 'aria-valuenow'
   | 'aria-valuetext'
   | 'onAccessibilityAction'
   | 'importantForAccessibility'
   | 'aria-hidden'
   | 'aria-modal'
   | 'role'
   | 'accessibilityLabelledBy'
   | 'aria-labelledby'
   | 'accessibilityLiveRegion'
   | 'aria-live'
   | 'accessibilityElementsHidden'
   | 'accessibilityViewIsModal'
   | 'onAccessibilityEscape'
   | 'onAccessibilityTap'
   | 'onMagicTap'
   | 'accessibilityIgnoresInvertColors'
   | 'accessibilityLanguage'
   | 'fill'
   | 'title'
   | 'clipPath'
   | 'marker'
   | 'mask'
   | 'delayLongPress'
   | 'delayPressIn'
   | 'delayPressOut'
   | 'disabled'
   | 'onLongPress'
   | 'onPress'
   | 'onPressIn'
   | 'onPressOut'
   | 'height'
   | 'width'
   | 'viewBox'
   | 'opacity'
   | 'fillOpacity'
   | 'fillRule'
   | 'stroke'
   | 'strokeWidth'
   | 'strokeOpacity'
   | 'strokeDasharray'
   | 'strokeDashoffset'
   | 'strokeLinecap'
   | 'strokeLinejoin'
   | 'strokeMiterlimit'
   | 'vectorEffect'
   | 'clipRule'
   | 'translate'
   | 'translateX'
   | 'translateY'
   | 'origin'
   | 'originX'
   | 'originY'
   | 'scale'
   | 'scaleX'
   | 'scaleY'
   | 'skew'
   | 'skewX'
   | 'skewY'
   | 'rotation'
   | 'x'
   | 'y'
   | 'transform'
   | 'markerStart'
   | 'markerMid'
   | 'markerEnd'
   | 'font'
   | 'fontStyle'
   | 'fontVariant'
   | 'fontWeight'
   | 'fontStretch'
   | 'textAnchor'
   | 'textDecoration'
   | 'wordSpacing'
   | 'kerning'
   | 'fontFeatureSettings'
   | 'fontVariantLigatures'
   | 'fontVariationSettings'
  > & { readonly preserveAspectRatio?: string | undefined } & {},
) => {
 const { width, height } = props
 return (
  <Svg
   //   xmlns="http://www.w3.org/2000/svg"
   width={width || 800}
   height={height || 800}
   fill="none"
   viewBox="0 0 24 24"
   {...props}
  >
   <Path
    stroke="#FFFFFF"
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={1.5}
    d="m3 3 18 18M10.5 10.677a2 2 0 0 0 2.823 2.823"
   />
   <Path
    stroke="#FFFFFF"
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={1.5}
    d="M7.362 7.561C5.68 8.74 4.279 10.42 3 12c1.889 2.991 5.282 6 9 6 1.55 0 3.043-.523 4.395-1.35M12 6c4.008 0 6.701 3.158 9 6a15.66 15.66 0 0 1-1.078 1.5"
   />
  </Svg>
 )
}
